M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Wed 27 Mar 2024 03:19:08 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-27T15:19:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.6614Y-3.8232
X5.6614Y-4.0508
T0
M30
