M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Mon 25 Mar 2024 11:47:04 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-25T23:47:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.6614Y-4.2062
X5.6614Y-4.4338
T0
M30
